### ISSUE TITLE
Update Building from source instructions in README.md

### ISSUE THREAD

**Issue by xingdavis** [mapbox/node-fontnik#114]
I try to build glyphs, and follow the example command line like:
build-glyphs "Open Sans Regular" glyphs/

throw error:
Error: /usr/local/lib/node_modules/fontnik/lib/fontnik.node: undefined symbol: _ZTIN6google8protobuf11MessageLiteE

I didn't know how to solve it.

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/local/lib/node_modules/fontnik/lib/fontnik.node: undefined symbol: _ZTIN6google8protobuf11MessageLiteE
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/fontnik/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by xingdavis** [comment]
my platform envinoments:
ubuntu14
node v0.12.17
npm 2.15.1
fontnik 0.4.4 (build from source)

**Comment by mikemorris** [comment]
@xingdavis It looks like you may be missing the `protobuf` dependency listed in [Building from source](https://github.com/mapbox/node-fontnik#building-from-source). For our CI environment (on OS X and Linux), we use [`scripts/install_mason.sh`](https://github.com/mapbox/node-fontnik/blob/master/scripts/install_mason.sh) to install dependencies - the building from source instructions should be updated to reflect this instead of recommending Homebrew.

**Comment by xingdavis** [comment]
It was passed to use the command line "npm install --unsafe-perm" 

But other problems have occus

node-fontnik$ sudo ./bin/build-glyphs "Open Sans Regular" glyphs/

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'Open Sans Regular'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/data/osm/osm2vectortiles/export/node-fontnik/bin/build-glyphs:19:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)

I found the fontstack in "fonts" dir
 ls -alh fonts/
![image](https://cloud.githubusercontent.com/assets/11851006/19546417/1ae00564-96c2-11e6-8f04-0a2b8468ea0e.png)

**Comment by mikemorris** [comment]
> node-fontnik$ sudo ./bin/build-glyphs "Open Sans Regular" glyphs/

Ahh, I think this should be `./bin/build-glyphs ./fonts/open-sans/OpenSans-Regular.ttf glyphs/` instead, with the second argument as a path to a font file. These docs and the CLI help need to be updated, thanks for catching this! =)
