### ISSUE TITLE
Error: Cannot find module './lib/fontnik.node'

### ISSUE THREAD

**Issue by KleggerKoder** [mapbox/node-fontnik#131]
Can't seem to get this working
Perhaps a permission issue on the binary source?

**Comment by mikemorris** [comment]
Could you post the command you ran and the entire error message please? It's possible that this is from attempting to install node-fontnik on an unsupported platform and the binary therefore failing to download.

**Comment by andest01** [comment]
I had success by creating a folder called `glyphs` via `mkdir glyphs` and then running `node ./bin/build-glyphs ./fonts/open-sans/OpenSans-Regular.ttf ./glyphs`

**Comment by innerpeacer** [comment]
I have the same problem.

When I run 'npm install' from the node-fontnik directory, I got the following:

> fontnik@0.5.0 install /Users/innerpeacer/Desktop/node-fontnik/node-fontnik
> node-pre-gyp install --fallback-to-build=true

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.5.0/Release/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fontnik@0.5.0 and node@7.7.4 (node-v51 ABI) (falling back to source compile with node-gyp)
  ACTION binding_gyp_action_before_build1_target_install_mason mason_packages
  TOUCH Release/obj.target/action_before_build1.stamp
  ACTION binding_gyp_action_before_build2_target_run_protoc_glyphs Release/obj/gen/glyphs.pb.cc
/bin/sh: ./mason_packages/.link/bin/protoc: No such file or directory
make: *** [Release/obj/gen/glyphs.pb.cc] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build=true" "--module=/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/lib/binding/fontnik.node" "--module_name=fontnik" "--module_path=/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/lib/binding"
gyp ERR! cwd /Users/innerpeacer/Desktop/node-fontnik/node-fontnik
gyp ERR! node -v v7.7.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build=true --module=/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/lib/binding/fontnik.node --module_name=fontnik --module_path=/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.7.4/bin/node" "/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=true"
node-pre-gyp ERR! cwd /Users/innerpeacer/Desktop/node-fontnik/node-fontnik
node-pre-gyp ERR! node -v v7.7.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp build --fallback-to-build=true --module=/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/lib/binding/fontnik.node --module_name=fontnik --module_path=/Users/innerpeacer/Desktop/node-fontnik/node-fontnik/lib/binding' (1)
npm WARN fontnik@0.5.0 No license field.
npm WARN The package mkdirp is included as both a dev and production dependency.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fontnik@0.5.0 install: `node-pre-gyp install --fallback-to-build=true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fontnik@0.5.0 install script 'node-pre-gyp install --fallback-to-build=true'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fontnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=true
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fontnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fontnik
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/innerpeacer/.npm/_logs/2017-04-27T06_08_09_468Z-debug.log

**Comment by innerpeacer** [comment]
downloading the pre-built binaries, get the following:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A08B8CE3D19047F6</RequestId>
<HostId>
ce1r82eP/B312E8qF5QdRc0bQIGIPFSbTELVsyg6aEZlHqdO3eD+7LCeBGoCr4qpXeYYcZht10o=
</HostId>
</Error>

**Comment by springmeyer** [comment]
@innerpeacer - we don't provide binaries yet for node v7. Stick with node v4 or v6 and it will work.

**Comment by innerpeacer** [comment]
Yeah, it works! Thanks very much

**Comment by lanjin** [comment]
still not working.
