### ISSUE TITLE
Leak in src/glyphs.cpp (RangeAsync)

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-fontnik#135]
I enabled Address sanitizer builds in #133 and they report a memory leak in freetype usage within a thread:

```
# outputs expected
not ok 2 Error: Command failed: /home/travis/build/mapbox/node-fontnik/bin/build-glyphs /home/travis/build/mapbox/node-fontnik/fonts/open-sans/OpenSans-Regular.ttf /home/travis/build/mapbox/node-fontnik/test/bin_output
================================================================= ==16361==
ERROR: LeakSanitizer: detected memory leaks Indirect leak of 348160 byte(s) in 256 object(s)
allocated from: #0 0x7fa73ea38c5c in __interceptor_malloc /home/ubuntu/mason/mason_packages/.build/llvm-3.9.1/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64:3
#1 0x7fa735b0aa24 in open_face (/home/travis/build/mapbox/node-fontnik/lib/fontnik.node+0x2e3a24)
#2 0x7fa735b02e96 in ft_open_face_internal (/home/travis/build/mapbox/node-fontnik/lib/fontnik.node+0x2dbe96)
#3 0x7fa735b03421 in FT_New_Memory_Face (/home/travis/build/mapbox/node-fontnik/lib/fontnik.node+0x2dc421)
#4 0x7fa735994ffb in node_fontnik::RangeAsync(uv_work_s*) /home/travis/build/mapbox/node-fontnik/build/../src/glyphs.cpp:281:35
#5 0xfa4710 in worker 
```

https://travis-ci.org/mapbox/node-fontnik/jobs/207251037#L395

**Comment by springmeyer** [comment]
solved by a0603e163354f06fa5d0d2f6
