### ISSUE TITLE
node-pre-gyp ERR! stack Error: Failed to execute

### ISSUE THREAD

**Issue by 609878415** [mapbox/node-fontnik#156]
Please help me,thanks
I got npm install succeed.
I got the following when I make:
[root@db06 node-fontnik]# make
V=1 ./node_modules/.bin/node-pre-gyp configure build --error_on_warnings=false --loglevel=error
make[1]: Entering directory `/home/db06/fontnik/node-fontnik/build'
  LD_LIBRARY_PATH=/home/db06/fontnik/node-fontnik/build/Release/lib.host:/home/db06/fontnik/node-fontnik/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../.; mkdir -p .; ./scripts/install_deps.sh
curl: (1) Protocol "https" not supported or disabled in libcurl

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[1]: *** [mason_packages] Error 2
make[1]: Leaving directory `/home/db06/fontnik/node-fontnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.0-957.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--error_on_warnings=false" "--loglevel=error" "--module=/home/db06/fontnik/node-fontnik/lib/binding/fontnik.node" "--module_name=fontnik" "--module_path=/home/db06/fontnik/node-fontnik/lib/binding" "--node_abi_napi=node-v48"
gyp ERR! cwd /home/db06/fontnik/node-fontnik
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --error_on_warnings=false --loglevel=error --module=/home/db06/fontnik/node-fontnik/lib/binding/fontnik.node --module_name=fontnik --module_path=/home/db06/fontnik/node-fontnik/lib/binding --node_abi_napi=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/db06/fontnik/node-fontnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 3.10.0-957.el7.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/db06/fontnik/node-fontnik/node_modules/.bin/node-pre-gyp" "configure" "build" "--error_on_warnings=false" "--loglevel=error"
node-pre-gyp ERR! cwd /home/db06/fontnik/node-fontnik
node-pre-gyp ERR! node -v v6.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --error_on_warnings=false --loglevel=error --module=/home/db06/fontnik/node-fontnik/lib/binding/fontnik.node --module_name=fontnik --module_path=/home/db06/fontnik/node-fontnik/lib/binding --node_abi_napi=node-v48' (1)
make: *** [release] Error 1

**Comment by 609878415** [comment]
I got npm install succeed.

**Comment by 609878415** [comment]
Linux CentOs7.
node v6.3.0.
npm 3.10.3.
I got npm install succeed.but not find "fontnik.node" in My Path/lib/binding/fontnik.node
then.
I do :npm install -g fontnik
and copy "fontnik.node" to My Path
cp /usr/local/lib/node_modules/fontnik/lib/binding/fontnik.node /home/db05/fontconvert/node-fontnik-0.5.0/lib/binding/
do transform agen:
node ./bin/build-glyphs ./fonts/open-sans/OpenSans-Regular.ttf ./glyphs
Succeed!!!
