### ISSUE TITLE
How to use the build-glyphs script

### ISSUE THREAD

**Issue by fnicollet** [mapbox/node-fontnik#61]
Hi,
On @yhahn advice in mapbox-gl-js (https://github.com/mapbox/mapbox-gl-js/issues/809) I am trying to extract all the pdfs for the Open Sans font for every charset for every font-face. 
His answer is to run the build-glyphs script from node-fontnik. 

I installed node-fontnik on a debian and ran the example 

> build-glyphs "OpenSans-Regular, Arial Unicode MS Regular" glyphs/
> I get the following error:
> Error: Failed to find face 'OpenSans-Regular' in font set 'Open Sans Regular, Arial Unicode MS Regular'

When I look into index.js, I can see an optionnal "FONTNIK_FONTS" env var that I tried to set to the /fonts dir with no success.

Should this script work out-of-the-box or does it need special configuration?

Thanks a lot!
Fabien

**Comment by maciekish** [comment]
I can't make this darn script work. I have installed fontnik but when i try to run it the following happens:

    % ./bin/build-glyphs "Open Sans Regular" glyphs/

    /Users/maciekish/Developer/Projects/node-fontnik/bin/build-glyphs:36
    fontnik.range(opts, function(err, zdata) {
            ^
    TypeError: Font buffer is not an object
        at writeGlyphs (/Users/maciekish/Developer/Projects/node-fontnik/bin/build-glyphs:36:13)
        at pop (/Users/maciekish/Developer/Projects/node-fontnik/node_modules/queue-async/queue.js:24:14)
        at Object.q.defer (/Users/maciekish/Developer/Projects/node-fontnik/node_modules/queue-async/queue.js:55:11)
        at Object.<anonymous> (/Users/maciekish/Developer/Projects/node-fontnik/bin/build-glyphs:28:7)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)

OpenSans-Regular.ttf is in fonts/opens-sans but i also installed it on Mac OS to rule that issue out. Still no go.

**Comment by lbud** [comment]
@maciekish thanks for calling this out — it looks like the `bin/` scripts haven't been updated since before a major interface change earlier this year. We're now using fontnik internally via [fontmachine](https://github.com/mapbox/fontmachine), but I've opened https://github.com/mapbox/node-fontnik/pull/98 to update these scripts.
